### ISSUE TITLE
Is batch tasks possible?

### ISSUE THREAD

**Issue by 1337-sys** [hibiken/asynq#352] opened 2021-11-19 15:23 UTC
Thank you very much for writing such a wonderful queue library. 

1.  I want to use it in production but I was wondering if batch processing is possible. I will bulk insert the data waiting in the queue to the db.

Finally, I would like to ask you something based on your experience.

2. A user has many notifications. I am writing these notifications to the database. But my db connection pool fills up immediately. Is it appropriate to open a queue for each user or to put all notifications in one queue?

queue -> uniqueUserID_notifications(per user)
queue -> notifications

Which would be more suitable? Can I delete notifications from someone with user id x when there is only one queue?

**Comment by hibiken** [comment] 2021-11-20 14:37
@1337-sys Thank you for opening an issue.

Let me make sure that I understood your questions correctly:

> I want to use it in production but I was wondering if batch processing is possible. I will bulk insert the data waiting in the queue to the db.

To use an example, if you enqueue task A, B and C to a queue. You want to handle these three tasks as a unit (e.g. in batch) instead of handling them individually. In other words, you want to group these tasks into one task that gets delivered to your `Handler`? If this is what you meant, there is an open feature-request: #339 and I will be working on it once I have a good design.

To answer the second question:
It's currently not possible to dynamically define which queue to consume tasks from in server's Config. A potential feature request would be to add support for prefix based queue matching when specifying the queues in server config.

>  Can I delete notifications from someone with user id x when there is only one queue?

You could use `Inspector.DeleteTask` to delete a task with queue name and task ID, but I'm not quite sure if this is what you are looking for.

If you could provide more context or examples, I can answer better to these questions :)

**Comment by hibiken** [comment] 2022-01-16 04:34
Duplicate of #339

**Closed by hibiken** 2022-01-16 04:34 UTC
