### ISSUE TITLE
[FEATURE REQUEST] save cron info and task to redis

### ISSUE THREAD

**Issue by newlife** [hibiken/asynq#330] opened 2021-09-24 12:15 UTC
**Is your feature request related to a problem? Please describe.**

when write  asynq client in python , to process tasks periodically ,I had to  enqueue task use some cron lib in python .
which is already there in asynq.

**Describe the solution you'd like**

save cron info in redis , use **Scheduler ** 's function to read and handle them. also ,can mange then in web ui

**Comment by crossworth** [comment] 2021-09-24 12:18
Related https://github.com/hibiken/asynq/issues/308#issuecomment-893980479

**Comment by hibiken** [comment] 2022-01-16 04:33
Duplicate of #308

**Closed by hibiken** 2022-01-16 04:33 UTC
Labels: enhancement
