### ISSUE TITLE
[FEATURE REQUEST] Backed Support In Memory or Embedded Database

### ISSUE THREAD

**Issue by lucy9x** [hibiken/asynq#382] opened 2022-01-19 16:28 UTC
Currently asynq only supports redis for backed. It would be great if asynq support in memory or embedded database like SQLite, BadgerDB, BoltDB... for backed

**Comment by hibiken** [comment] 2022-02-01 14:57
Duplicate of #173

**Closed by hibiken** 2022-02-01 14:57 UTC
Labels: enhancement

**Comment by ixugo** [comment] 2025-04-15 18:13
try it [github.com/ixugo/nsqite](https://github.com/ixugo/nsqite) ，support memory，Use gorm to support database transactions
