### ISSUE TITLE
[BUG] WARN: recoverer: could not move task to archive: NOT FOUND

### ISSUE THREAD

**Issue by TopScrew** [hibiken/asynq#274] opened 2021-05-20 06:43 UTC
**Describe the bug**
WARN: recoverer: could not move task to archive: NOT FOUND

**Expected behavior**
![image](https://user-images.githubusercontent.com/35072495/118931458-a1b35d00-b979-11eb-8ca1-b8294be8162c.png)

**Screenshots**

**Environment (please complete the following information):**
 - OS:  Linux
 - Version of `asynq` v0.17.1

**Comment by hibiken** [comment] 2021-05-20 12:56
@TopScrew Thank you for reporting this issue.

Could you give me more details so that I can reproduce this bug?

**Comment by hibiken** [comment] 2021-06-06 13:44
Hi @TopScrew, are you still seeing the issue? Or were you able to figure it out?

**Comment by hibiken** [comment] 2021-06-09 13:10
Closing this for now since no follow up.
Feel free to reopen the issue if anyone is encountering the same bug.

**Closed by hibiken** 2021-06-09 13:10 UTC
Labels: bug

**Comment by TheDhejavu** [comment] 2023-03-22 10:57
same issue here: This bug is hard to re-create, i could only think of two things
- When the redis configuration was changed to delete LRU 
- When redis storage was full

<img width="1123" alt="Screen Shot 2023-03-22 at 11 52 00 AM" src="https://user-images.githubusercontent.com/19678915/226881991-0afa699d-b1a0-4150-a978-410793327969.png">

**Comment by yeqown** [comment] 2023-07-30 07:06
![image](https://github.com/hibiken/asynq/assets/27146233/4815e637-953d-4731-b0df-88db45f939e8)

I got this issue too, I debug and monitor the Redis command, and I got the above screenshot, and refer to the `archiveCmd` lua code:

```go
// KEYS[1] -> asynq:{<qname>}:t:<task_id>
// KEYS[2] -> asynq:{<qname>}:active
// KEYS[3] -> asynq:{<qname>}:lease
// KEYS[4] -> asynq:{<qname>}:archived
// KEYS[5] -> asynq:{<qname>}:processed:<yyyy-mm-dd>
// KEYS[6] -> asynq:{<qname>}:failed:<yyyy-mm-dd>
// KEYS[7] -> asynq:{<qname>}:processed
// KEYS[8] -> asynq:{<qname>}:failed
// -------
// ARGV[1] -> task ID
// ARGV[2] -> updated base.TaskMessage value
// ARGV[3] -> died_at UNIX timestamp
// ARGV[4] -> cutoff timestamp (e.g., 90 days ago)
// ARGV[5] -> max number of tasks in archive (e.g., 100)
// ARGV[6] -> stats expiration timestamp
// ARGV[7] -> max int64 value
var archiveCmd = redis.NewScript(`
if redis.call("LREM", KEYS[2], 0, ARGV[1]) == 0 then
  return redis.error_reply("NOT FOUND")
end
if redis.call("ZREM", KEYS[3], ARGV[1]) == 0 then
  return redis.error_reply("NOT FOUND")
end
redis.call("ZADD", KEYS[4], ARGV[3], ARGV[1])
redis.call("ZREMRANGEBYSCORE", KEYS[4], "-inf", ARGV[4])
redis.call("ZREMRANGEBYRANK", KEYS[4], 0, -ARGV[5])
redis.call("HSET", KEYS[1], "msg", ARGV[2], "state", "archived")
local n = redis.call("INCR", KEYS[5])
if tonumber(n) == 1 then
	redis.call("EXPIREAT", KEYS[5], ARGV[6])
end
local m = redis.call("INCR", KEYS[6])
if tonumber(m) == 1 then
	redis.call("EXPIREAT", KEYS[6], ARGV[6])
end
local total = redis.call("GET", KEYS[7])
if tonumber(total) == tonumber(ARGV[7]) then
   	redis.call("SET", KEYS[7], 1)
   	redis.call("SET", KEYS[8], 1)
else
  	redis.call("INCR", KEYS[7])
   	redis.call("INCR", KEYS[8])
end
return redis.status_reply("OK")`)
```

Conclusion is the `qname` (queue name) is empty causes this output, but why the `qname` is empty, I'm still following the source code, since I'm new guy as for `asynq` source code.

**Comment by yeqown** [comment] 2023-07-30 07:26
By following the calling stack, I found `recoverLeaseExpiredTasks` call `archiveCmd`, and here provide an `ZERO` value of `TaskMessage` it's queueName is empty.

<img width="1239" alt="image" src="https://github.com/hibiken/asynq/assets/27146233/9b68ea3f-2963-43f5-9f37-8c97c1b9eb64">

More deeply reading the source code, github.com/hibiken/asynq@v0.24.1/internal/rdb/rdb.go:1293 `ListLeaseExpired` calls `base.DecodeMessage`, and it returns a ZERO value even though `data` parameter is an empty byte slice.

<img width="1395" alt="image" src="https://github.com/hibiken/asynq/assets/27146233/69906042-0ede-408e-a7cf-c7b14e45ee9f">

**Comment by bingtianyiyan** [comment] 2024-01-31 03:19
<img width="1178" alt="1706671082956" src="https://github.com/hibiken/asynq/assets/48984656/6408cd38-56c8-4525-8c10-8b343f17dd18">
also have this problem

**Comment by kamikazechaser** [comment] 2024-01-31 06:22
@bingtianyiyan What version of asynq are you using? Try using `@master` and see if the issue still persists.
