### ISSUE TITLE
[QUESTION] - Looking for some suggestions on data aggregation

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#501] opened 2022-06-22 11:13 UTC
### Discussed in https://github.com/hibiken/asynq/discussions/500

<div type='discussions-op-text'>

<sup>Originally posted by **sujit-baniya** June 22, 2022</sup>
Hello, 
I've been trying to implement Workflow using this library.

https://github.com/sujit-baniya/asynq/blob/master/flow.go

For the purpose, I've implemented flow and this example works for simple Edge and Node implementation

https://github.com/sujit-baniya/asynq/blob/master/examples/asynq_worker.go

The example works for 
1) An edge with single input and single output
2) A loop with single input and single output

I'm trying find solution where a edge/loop has multiple output. Since there would be multiple output, at some point it is required to combine such data.

For e.g.
NodeA with key A
NodeB with key B (generates phone_valid field)
NodeC with key C (generates email_valid field)
NodeD with key D

Edge is created from A -> B
Edge is created from A -> C
Edge is created from B -> D
Edge is created from C -> D

I'm trying to get aggregated data received from above flow.

If I pass data like `{"phone": "123456789", "email": "abc@example"}` to Node A, I would be expecting `{"phone": "123456789", "email": "abc@example", "phone_valid": true, "email_valid": true}` on Node D

Please suggest some ideas.</div>

**Comment by hibiken** [comment] 2022-06-26 19:42
Duplicate of #500

**Closed by hibiken** 2022-06-26 19:42 UTC
