### ISSUE TITLE
[BUG] Redis Error when enqueuing using Goroutine

### ISSUE THREAD

**Issue by sujit-baniya** [hibiken/asynq#243] opened 2021-02-13 16:51 UTC
When many tasks are enqueued within multiple goroutine, the error occurs stating: `panic: redis: connection pool timeout`

**To Reproduce**
```go
        var wg sync.WaitGroup
	for i := 0; i <= 100000; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			// Create a task with typename and payload.
			t1 := asynq.NewTask(taskType, payload)
			// Process the task immediately.
			_, err := Client.Enqueue(t1, asynq.Queue(queue))
			if err != nil {
				panic(err)
			}
		}()
	}
	wg.Wait()
```

**Comment by hibiken** [comment] 2021-04-13 14:59
Duplicate of #256. 
You can tune dial/read/write timeout now via `RedisConnOpt` when instantiating `Client` and `Server`.

Feel free to re-open the issue if you are still having this issue 👍

**Closed by hibiken** 2021-04-13 14:59 UTC
Labels: bug
