### ISSUE TITLE
[FEATURE REQUEST] Task header ability

### ISSUE THREAD

**Issue by Goxiaoy** [hibiken/asynq#497] opened 2022-06-21 08:28 UTC
**Is your feature request related to a problem? Please describe.**
https://github.com/hibiken/asynq/issues/321
**Describe the solution you'd like**

Provider new asynq.Option to set custom header like `http.header` or `map[string]string`
Or like 
```
type RecordHeader struct {
	Key   []byte
	Value []byte
}
```
This is helpful for tracing

```
func SetTracingOption(ctx context.Context) asynq.Option {
	//recover header
	var header transport.Header = propagation.HeaderCarrier(http.Header{})
	ctx = propagator.Extract(ctx, header)
	//TODO ability to set header
	panic("unimplemented")
}
```

**Additional context**
See
https://github.com/Shopify/sarama/blob/7a92423e79f75314489f9694be4013aaf5fd3593/record.go#L15-L18

**Comment by hibiken** [comment] 2022-06-26 19:48
Duplicate of #393

**Closed by hibiken** 2022-06-26 19:48 UTC
Labels: enhancement
