### ISSUE TITLE
[FEATURE REQUEST] Schedule for retry / mark task as process later

### ISSUE THREAD

**Issue by sdklab007** [hibiken/asynq#316] opened 2021-08-24 05:33 UTC
**Is your feature request related to a problem? Please describe.**
Currently, we are using Asynq for checking the status of the transaction that gets proceed by another system. Sometimes the transaction goes on the "PENDING" status, hence we would want Asynq to retry until the transaction status is either FAILED/SUCCESS.

**Describe the solution you'd like**
Ability to retry the task without creating an Error. Since the error rate would increase when it's actually not an error.

**Describe alternatives you've considered**
We are currently returning an error if the transaction status is "PENDING" so that Asynq can retry the task by itself.  The problem here is, the Error rate will increase, overall its not even an error here, we only want to say Asynq to retry this task later.
```
func HandleTransactionStatusTask(ctx context.Context, t *asynq.Task) error {
    var p MyPayLoad
    if err := json.Unmarshal(t.Payload(), &p); err != nil {
        return fmt.Errorf("json.Unmarshal failed: %v: %w", err, asynq.SkipRetry)
    }
   // result of some external API call 
   if result == "PENDING" {
       return  errors.New("Still pending"),
   }
    return nil
}
```

**Comment by hibiken** [comment] 2021-08-25 13:13
@sdklab007 Thank you for opening this issue!
I responded in the issue #273, please take a look!

This is a duplicate of #273 I'll close this one and move the discussion to the other issue.

**Closed by hibiken** 2021-08-25 13:13 UTC
Labels: enhancement
