### ISSUE TITLE
[BUG] Got panic when starting service

### ISSUE THREAD

**Issue by hieunguyen1809** [hibiken/asynq#403] opened 2022-02-20 14:43 UTC
Hi guys, today I found that my service suddenly panic with this error. I'm using asynq version 0.18.6, not sure how can I fix it.

```
panic: uuid: Parse(): invalid UUID length: 0
goroutine 32 [running]:
github.com/google/uuid.MustParse(0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/google/uuid@v1.3.0/uuid.go:163 +0x125
github.com/hibiken/asynq/internal/base.DecodeMessage(0x1ce0618, 0x0, 0x0, 0x1ce0618, 0x0, 0x0)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.6/internal/base/base.go:264 +0x105
github.com/hibiken/asynq/internal/rdb.(*RDB).ListDeadlineExceeded(0xc0000301c0, 0xc07cb23f512ab159, 0xfffffff90cdcfcda, 0x1ca8b40, 0xc0008441c0, 0x3, 0x4, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.6/internal/rdb/rdb.go:687 +0x42a
github.com/hibiken/asynq.(*recoverer).recover(0xc000828410)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.6/recoverer.go:82 +0x8d
github.com/hibiken/asynq.(*recoverer).start.func1(0xc000364250, 0xc000828410)
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.6/recoverer.go:63 +0x6e
created by github.com/hibiken/asynq.(*recoverer).start
	/go/pkg/mod/github.com/hibiken/asynq@v0.18.6/recoverer.go:61 +0x65
```

**Comment by hibiken** [comment] 2022-02-22 17:00
@hieunguyen1809 Thank you for reporting an issue! (Sorry for the delay in response).

Could you provide the output from these commands? (Ideally no server is running while you run these commands)
(substitude the `<qname>` with your queue name)

```
$ redis-cli zrange asynq:{<qname>}:deadlines 0 -1
```

The above command will give you the list of task IDs and use the IDs to run the following command (substitude <task_id> with the ID returned from the previous command).

```
$ redis-cli hgetall asynq:{<qname>}:t:<task_id>
```

---

To get more context, did you happen to upgrade asynq version from v0.17.x to v.18.x? If so, there were a few breaking changes between these versions and the upgrade guide is documented [here](https://github.com/hibiken/asynq/wiki/Version-Upgrade-Guide-(from-0.17-to-0.18)).

Let me know if you have any questions!

**Comment by hieunguyen1809** [comment] 2022-02-24 08:40
I do not have access the prod redis directly but the server start normally after I upgrade to the latest version 0.21.0. Sorry, I'm busy these days so I forgot to reply.

**Comment by hieunguyen1809** [comment] 2022-02-24 08:41
I do not have access the prod redis directly but the server start normally after I upgrade to the latest version 0.21.0. Sorry, I'm busy these days so I forgot to reply.

**Comment by hibiken** [comment] 2022-02-24 13:39
Got it. I'll close this for now since we can't reproduce.

**Closed by hibiken** 2022-02-24 13:39 UTC
Labels: bug

**Comment by ahloul** [comment] 2023-04-16 11:13
@hibiken I have the same issue
![image](https://user-images.githubusercontent.com/5293846/232305484-b8357a6d-06fe-4a7a-8b41-2024bbae98ce.png)

there are some empty values too
![image](https://user-images.githubusercontent.com/5293846/232305506-ce5bc8fc-7121-4daf-add5-730610186c0b.png)

my version is v0.18.4
