### ISSUE TITLE
Workflow Support

### ISSUE THREAD

**Issue by Milk-Tang** [hibiken/asynq#737] opened 2023-09-08 02:52 UTC
**Is your feature request related to a problem? Please describe.**
Running a single asynchronous task is fine but often I will want to design a workflow of tasks to be executed in an orchestrated way.

**Describe the solution you'd like**
I really want **asynq** to be better, so I suggest the a workflow support like the feature of [workflow](https://github.com/RichardKnop/machinery/tree/master#workflows) in  [machinery](https://github.com/RichardKnop/machinery)

**Comment by hibiken** [comment] 2023-09-18 02:20
@Milk-Tang Thank you for creating this feature request.
Marking this as a duplicate of #244

**Closed by hibiken** 2023-09-18 02:20 UTC
Labels: enhancement
