### ISSUE TITLE
[FEATURE REQUEST] Driver for NATS so we get geo physical Load balancing and Failover

### ISSUE THREAD

**Issue by gedw99** [hibiken/asynq#368] opened 2021-12-17 19:15 UTC
**Is your feature request related to a problem? Please describe.**

I need geo physical load balancing and NATS provides that out of the box.

NATS can run for example 3 servers in each continent. You typically setup 3 in a cluster in each continent.

the nats.go client will automatically connect to the nearest one and automatically failover and then reconnect when a closer server or cluster comes back up.

**Describe the solution you'd like**

the Redis driver can still be kept but I would like to add a NATS driver also.

NATS server driver that does what the current Redis driver does. This driver will use the nats.go golang client.

**Describe alternatives you've considered**

I think Redis enterprise has clustering and failover . Nats is free and open and has this clustered LB and failover functionality.

**Additional context**

https://github.com/nats-io/nats.go

https://github.com/nats-io/nats-server

Nats also has accounts , users that are hierarchical and so you get multi tenant for free . 

https://github.com/nats-io/nsc

Nats also has cluster wide monitoring 

https://github.com/nats-io/nats-surveyor

**Comment by hibiken** [comment] 2021-12-18 15:10
@gedw99 Thank you for opening this issue! 
Adding support for other message brokers are on our long-term roadmap. If you need this feature soon, it'd recommend look for other solutions since we don't have specific timeline for when this will be worked on.

Related issue: #173

**Comment by c-nv-s** [comment] 2021-12-31 22:15
Just to let you know this would be an awesome feature. 
I understand that it is complex and low-priority... but it can help people reduce the complexity of thier stacks.

**Comment by hibiken** [comment] 2022-01-16 04:35
Duplicate of #173

**Closed by hibiken** 2022-01-16 04:35 UTC
Labels: enhancement, designing
