### ISSUE TITLE
[BUG] Task stuck at active state

### ISSUE THREAD

**Issue by hieunguyen1809** [hibiken/asynq#495] opened 2022-06-20 13:49 UTC
**Describe the bug**
Many tasks are stuck at running state and I cannot cancel or delete them. Also I realize that "Next Process Time" info always change to current timestamp when I reload the page (using asynmon)

**To Reproduce**
Steps to reproduce the behavior (Code snippets if applicable):
Cannot reproduce but I ensure that workers are not crash when processing. It happen when I run many tasks at the same time (around ~ 1000 tasks)

**Screenshots**
<img width="703" alt="Screen Shot 2022-06-20 at 20 45 18" src="https://user-images.githubusercontent.com/57081022/174616345-38a88a68-72fc-4a61-8e3d-006b9bd2325d.png">

**Environment (please complete the following information):**
 - OS: Linux alpine:3.13
 - Version of `asynq` package: v0.22.1

**Comment by hibiken** [comment] 2022-06-20 22:58
@hieunguyen1809 Thank  you for opening this issue. 

Would you mind answering the questions asked in [this commen](https://github.com/hibiken/asynq/issues/420#issuecomment-1075146735)t?

**Comment by hibiken** [comment] 2022-06-26 19:44
Duplicate of #420 

@hieunguyen1809 if you are still having this issue, please see the comment above!

**Closed by hibiken** 2022-06-26 19:44 UTC
Labels: bug
