### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by carrymec** [hibiken/asynq#358] opened 2021-11-22 06:49 UTC
### Discussed in https://github.com/hibiken/asynq/discussions/357

<div type='discussions-op-text'>

<sup>Originally posted by **carrymec** November 22, 2021</sup>
https://github.com/hibiken/asynq/blob/9f2c321e9804901f06b58e82f9e0ce4125d80b74/internal/rdb/rdb.go#L871

![image](https://user-images.githubusercontent.com/36873164/142816180-5455250e-59d4-4445-9495-f4eb2992f038.png)

when line 679 for range this data will 'panic(`uuid: Parse(` + s + `): ` + err.Error())'
![image](https://user-images.githubusercontent.com/36873164/142816281-17ba7b89-373f-4f8c-8b05-ecb740d54d99.png)

</div>

**Comment by carrymec** [comment] 2021-11-22 06:49
![image](https://user-images.githubusercontent.com/36873164/142816635-c8ac3406-a1e8-4d8f-9467-dcf7636344e9.png)

**Comment by carrymec** [comment] 2021-11-22 06:50
i dont know when this data created

**Comment by hibiken** [comment] 2021-11-22 14:02
@carrymec thank you for opening an issue.

Could you describe the steps to reproduce the bug?

**Comment by carrymec** [comment] 2021-11-24 03:07
i remove all asynq:{default}:t* keys

**Comment by hibiken** [comment] 2021-12-20 14:20
I don't believe this is a bug of the library since user deleted tasks from redis manually. Closing this.

**Closed by hibiken** 2021-12-20 14:20 UTC
